
title: Mon CV
url: 'http://unouss.free.fr'
baseurl: '/CV' #change it according to your repository name



# Profile information
yourname: Younoussa Sow  ## put your name
title: '&Eacute;tudiant en DUT Informatique'  ## your title
location: IUT-A , Villeneuve D'ascq


## Social Profiles
facebook: https://fb.me/uNouss  ## your facebook account url
twitter: https://www.twitter.com/uNous5 ## your twitter account url
twitter: https://framapiaf.org/uNouss  ## your twitter account url
linkedin: https://www.linkedin.com  ## your linkedin account url
codecademy: https://codecademy.com/uNouss  ## you dribbble account url
#foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
