
title: Mon CV
url: 'http://unouss.free.fr'
baseurl: '/CV' #change it according to your repository name



# Profile information
yourname: Younoussa Sow  ## put your name
title: '&Eacute;tudiant en DUT Informatique'  ## your title
location: IUT-A , Villeneuve D'ascq


## Social Profiles
facebook: https://fb.me/uNouss  ## your facebook account url
twitter: https://framapiaf.org/@uNouss  ## your twitter account url
linkedin: https://www.linkedin.com/in/younoussa-sow-334850150  ## your linkedin account url
codecademy: https://codecademy.com/uNouss  ## you dribbble account url
github: https://github.com/uNouss  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
